torchrun --nproc_per_node 4 -m training.main --batch-size=16 --lr=1e-5 --wd=0.1 --epochs=6 --workers=4 \
--model EVA02-CLIP-B-16 --pretrained eva --warmup 1000  --zeroshot-frequency 1 \
--method-type region_clip --dataset-type region_clip \
--test-type coco_panoptic --train-data data/coco/coco_pseudo_4764.json \
--val-data data/coco/annotations/panoptic_val2017.json \
--train-embed-path metadata/coco_pseudo_4764_clip_hand_craft_EVACLIP_ViTB16.npy \
--embed-path metadata/coco_panoptic_clip_hand_craft_EVACLIP_ViTB16.npy --train-image-root data/coco/train2017 \
--val-image-root data/coco/val2017  --cache-dir checkpoints/EVA02_CLIP_B_psz16_s8B.pt --log-every-n-steps 50 \
--lock-image --save-frequency 1 --lock-image-unlocked-groups 12 --extract-type="v2" \
--downsample-factor 16 --det-image-size 512 \
--alpha 0.7